In [6]:
from numpy import array
from numpy import random
from numpy import dot
from scipy.special import softmax
 
# encoder representations of four different words
word_1 = array([1, 0, 0])
word_2 = array([0, 1, 0])
word_3 = array([1, 1, 0])
word_4 = array([0, 0, 1])
 
# stacking the word embeddings into a single array
words = array([word_1, word_2, word_3, word_4])
 
print(words)


[[1 0 0]
 [0 1 0]
 [1 1 0]
 [0 0 1]]


In [8]:
# generating the weight matrices
random.seed(42)
W_Q = random.randint(3, size=(3, 3))
W_K = random.randint(3, size=(3, 3))
W_V = random.randint(3, size=(3, 3))
 
print(W_Q)
print(W_K)
print(W_V)


[[2 0 2]
 [2 0 0]
 [2 1 2]]
[[2 2 2]
 [0 2 1]
 [0 1 1]]
[[1 1 0]
 [0 1 1]
 [0 0 0]]


In [10]:
# generating the queries, keys and values
Q = words @ W_Q
K = words @ W_K
V = words @ W_V
 
print(Q) 
print(K)
print(V)

[[2 0 2]
 [2 0 0]
 [4 0 2]
 [2 1 2]]
[[2 2 2]
 [0 2 1]
 [2 4 3]
 [0 1 1]]
[[1 1 0]
 [0 1 1]
 [1 2 1]
 [0 0 0]]


In [11]:
# scoring the query vectors against all key vectors
scores = Q @ K.transpose()
print(scores)

[[ 8  2 10  2]
 [ 4  0  4  0]
 [12  2 14  2]
 [10  4 14  3]]


In [17]:
# computing the weights by a softmax operation
weights = softmax(scores / K.shape[1] ** 0.5, axis=1)
 
print(weights)
np.sum(weights, axis=1)

[[2.36089863e-01 7.38987555e-03 7.49130386e-01 7.38987555e-03]
 [4.54826323e-01 4.51736775e-02 4.54826323e-01 4.51736775e-02]
 [2.39275049e-01 7.43870015e-04 7.59237211e-01 7.43870015e-04]
 [8.99501754e-02 2.81554063e-03 9.05653685e-01 1.58059922e-03]]


array([1., 1., 1., 1.])

In [ ]:
# computing the attention by a weighted sum of the value vectors
attention = weights @ V
 
print(attention)

In [13]:
np.sum(attention, axis=1)

array([3.48348102, 2.81930529, 3.51698668, 3.80814617])